cmake_minimum_required(VERSION 3.4...3.18)
project(cirbo)

set(CMAKE_CXX_STANDARD 17 CACHE STRING "C++ version selection")  # or 11, 14, 17, 20
set(CMAKE_CXX_STANDARD_REQUIRED ON)  # optional, ensure standard is supported
set(CMAKE_CXX_EXTENSIONS OFF)  # optional, keep compiler extensions off

option(DISABLE_ABC_CEXT "Controls if ABC should be compiled." OFF)

# Force mockturtle to not compile heavy examples.
# Note: must be before mockturtle's CMakeLists is added.
SET(MOCKTURTLE_EXAMPLES OFF CACHE BOOL "Build examples" FORCE)

add_subdirectory(third_party/pybind11)
add_subdirectory(third_party/mockturtle)

pybind11_add_module(mockturtle_wrapper extensions/mockturtle_wrapper/src/module.cpp)
target_link_libraries(mockturtle_wrapper PRIVATE mockturtle)
target_include_directories(mockturtle_wrapper PRIVATE third_party)

# ABC related libs can be disabled using environment variable.
IF(NOT DISABLE_ABC_CEXT)
    # Disabled because it requires gnu readline to be installed on build
    # machine, but is not necessary for the ABC compilation as library.
    set(READLINE_FOUND FALSE CACHE BOOL "" FORCE)

    add_subdirectory(third_party/abc)

    # ABC exports its private -fno-exceptions flag to consumers.
    # Remove it from the interface; ABC itself is still built with this flag.
    get_target_property(ABC_INTERFACE_OPTIONS libabc-pic INTERFACE_COMPILE_OPTIONS)

    if(ABC_INTERFACE_OPTIONS)
        set(ABC_FILTERED_INTERFACE_OPTIONS)

        foreach(OPTION ${ABC_INTERFACE_OPTIONS})
            if(NOT OPTION MATCHES "fno-exceptions")
                list(APPEND ABC_FILTERED_INTERFACE_OPTIONS "${OPTION}")
            endif()
        endforeach()

        set_target_properties(libabc-pic PROPERTIES
            INTERFACE_COMPILE_OPTIONS "${ABC_FILTERED_INTERFACE_OPTIONS}"
        )
    endif()

    pybind11_add_module(abc_wrapper extensions/abc_wrapper/src/module.cpp)
    target_link_libraries(abc_wrapper PRIVATE libabc-pic)
    target_include_directories(abc_wrapper PRIVATE third_party)

    # Fixes case in CI, when ABC compilation
    # fails with "#error unknown platform" on
    # macos runners (both intel and apple silicon).
    if(NOT WIN32)
      target_compile_definitions(abc_wrapper PRIVATE ABC_USE_STDINT_H)
      target_compile_definitions(libabc-pic PRIVATE ABC_USE_STDINT_H)
      if(TARGET libabc)
        target_compile_definitions(libabc PRIVATE ABC_USE_STDINT_H)
      endif()
    endif()

    if (MSVC)
      # Fixes Windows build: `pthreads-win32` tried to redefine `timespec`.
      target_compile_definitions(libabc-pic PRIVATE HAVE_STRUCT_TIMESPEC=1)
      if(TARGET libabc)
        target_compile_definitions(libabc PRIVATE HAVE_STRUCT_TIMESPEC=1)
      endif()
    endif()
ENDIF(NOT DISABLE_ABC_CEXT)
